/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData cough = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData temperature = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData headache_1_ = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData nose = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData sore_throat = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData hand_wash = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData weak = IconData(0xe806, fontFamily: _kFontFam);
}
